# Generated by Django 4.2.6 on 2023-11-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
    ]
