# Generated by Django 4.2.6 on 2023-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FamousFood',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
