# Generated by Django 4.2.6 on 2023-11-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_category_external_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
