# Generated by Django 4.2.6 on 2023-11-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_fooditem_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='name',
        ),
    ]
