# Generated by Django 4.2.6 on 2023-11-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_fooditem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(default='https://example.com/default_image.jpg'),
        ),
    ]
