# Generated by Django 4.2.6 on 2023-10-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Festival',
        ),
    ]
