# Generated by Django 4.2.6 on 2023-11-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='description',
        ),
        migrations.AddField(
            model_name='culture',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='cultures.culture'),
        ),
    ]
